#!/usr/bin/env bash

set -eu -o pipefail

tag=$1

id=$(
  docker ps |
    tail -n+2 |
    grep -E '^\S+\s+'"$tag"'\s+' |
    awk '{print $1}' \
  || true
)

if [[ -n $id ]]; then
  echo "$id"
  exit 0
else
  exit 1
fi
